// console.log("Hello, World");

// function sum(...numbers) {
//     return numbers.reduce((acc,curr)=> acc + curr , 0);
// }

// sum(1 ,2,45,3 );
// sum(3,4,5,2,1);
// sum(32,43,53,13);

// class Person {
//     constructor(name, age) {
//         this.name = name;
//         this.age = age;
//     }

//     walk() {
//         console.log(this.name + " is walking.");
//     }
//     run() {
//         console.log(this.name + " is running.");
//     }
// }
// let person1 = new Person("Safak", 19);
// console.log("Name:", person1.name);
// console.log("Age:", person1.age);
// person1.walk();
// person1.run();



// class Person{
//     name;
//     age;
//     dist;
//     constructor(name, age, dist){
//     this.name = name ;
//     this.age =age;
//     this.dist=dist;
//     }
//     walk(){
//         console.log(`${this.name} is walking`);
        
//     }
//     run(){
//         console.log(`${this.name} is running`);
//     }
// }

// let person1= new Person("Safak",19,"chandauli");
// console.log(person1);

// let saif= new Person("Saif ullah",92,"praygraj");
// console.log(saif);

// person1.run();
// saif.walk();
// saif.run();

 